services:
  - type: web
    name: studynotion-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
